### ISSUE TITLE
PostgreSQL database dump

### ISSUE THREAD

**Issue by julsraemy** [Participatory-Image-Archives/pia-data-model#7]
When trying to import the PostgreSQL database dump ([pia_populated.sql](https://raw.githubusercontent.com/Participatory-Image-Archives/pia-data-model/main/dbml%20model/pia_populated.sql)), the following error is prompted: 

```
ERROR:  syntax error at or near "1"
LINE 1043: 1 336837 Société suisse des traditions populaires, Section F...
           ^
SQL state: 42601
Character: 24373
```

@thgie: "Maybe it is due to an error in the schema or how pgAdmin does the plain SQL export."

**Comment by thgie** [comment]
This seems to be a problem specific to pgadmin. The import of the populated sql dump via command line interface works fine. Make sure to grant privileges on a specific user after import.

```bash
# change to postgres user
sudo su - postgres

# import sql dump
psql pia < pia_populated.sql

# connect to database pia
psql
\c pia;

# grant everything to user pia
grant all privileges on all tables in schema public to pia;
```
